version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    environment:
      TZ: 'Australia/Adelaide'
      WEBPASSWORD: password
      VIRTUAL_HOST: pihole.host.domain.com
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      nginx-proxy:
        ipv4_address: 172.29.0.2

networks:
  default:
    external:
      name: nginx-proxy
